@startuml

title WODMaster-ER-Diagram

entity "t_user" {
    + id [PK]
    == 
    first_name: 名 varchar(30) Not NUll
    last_name: 性 varchar(30) Not NULL
    email: メール varchar(100) Not NUll
    pass: パスワード varchar(30) Not NUll
}

package strength {
    entity "t_sod" {
        + id [PK]
        ==
        name: 名前 varchar(30) Not NULL
        created_user_id: [FK(t_user.id)]
        created: 生成時間 datetime
        public: 公開ステータス bool
    }

    entity "t_set" {
        + id [PK]
        ==
        # sod_id: [FK(t_sod.id)]
        # strength_id: [FK(t_strength_master.id)]
        location: 配置 unsigned int(10)
        time: セット時間 time
        reps: レップス unsigned int(10)
    }

    entity "t_strength_master" {
        + id [PK]
        ==
        strength_name ストレングス名: varchar(100)
    }
}

package history {
    entity "t_user_sod" {
        + id [PK]
        ==
        user_id: [FK(t_user.id)]
        sod_id: [FK(t_sod.id)]
        created: 生成時間 datetime
        comment: text
    }

    entity "t_score" {
        + id [PK]
        ==
        user_sod_id: [FK(t_user_sod.id)]
        location: 配置 unsigned int(10)
        weight: 重さ float
    }
}


t_user ||--o{ t_user_sod
t_user ||--o{ t_sod

t_sod ||--o{ t_user_sod
t_sod ||--|{ t_set

t_strength_master ||--o{ t_set

t_user_sod ||--{ t_score

@enduml